Running on host: studgpu-node09.inf.ethz.ch
In directory: /cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2
Starting on: Thu May 2 21:46:28 CEST 2024
SLURM_JOB_ID: 11778
Using cache found in /home/owendu/.cache/torch/hub/facebookresearch_WSL-Images_main
CUDA enabled
  0%|          | 0/394 [00:00<?, ?it/s]/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-23.947208862000004,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.9577378370000034,)
  0%|          | 1/394 [00:34<3:48:31, 34.89s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.0329040660000004,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.4926170940000034,)
  1%|          | 2/394 [00:36<1:38:11, 15.03s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026542715000005046,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.34665717200000046,)
  1%|          | 3/394 [00:37<56:33,  8.68s/it]  --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026702272999997945,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3136096530000003,)
  1%|          | 4/394 [00:38<37:02,  5.70s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02648959599999756,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.33070661100000365,)
  1%|▏         | 5/394 [00:39<26:17,  4.05s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026075908000002812,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3254516099999947,)
  2%|▏         | 6/394 [00:40<19:48,  3.06s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.025814660000001766,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.32260798100000443,)
  2%|▏         | 7/394 [00:41<15:41,  2.43s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.028124469000005092,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.34478362499999804,)
  2%|▏         | 8/394 [00:44<16:10,  2.51s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026521967000000757,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3333472999999998,)
  2%|▏         | 9/394 [00:45<13:20,  2.08s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02855207799999704,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.319620246999996,)
  3%|▎         | 10/394 [00:48<14:23,  2.25s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026113978999994458,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.32394993699999475,)
  3%|▎         | 11/394 [00:49<12:11,  1.91s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03216799800000558,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31749619899999715,)
  3%|▎         | 12/394 [00:52<13:53,  2.18s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03057017600000478,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3331608430000017,)
  3%|▎         | 13/394 [00:53<11:50,  1.86s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03056872500000196,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3538538270000018,)
  4%|▎         | 14/394 [00:55<12:29,  1.97s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027578579999996577,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31414997000000255,)
  4%|▍         | 15/394 [00:56<10:51,  1.72s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026296984000005352,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.46436594099999695,)
  4%|▍         | 16/394 [00:59<12:23,  1.97s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02640186,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.30744827599999525,)
  4%|▍         | 17/394 [01:00<10:45,  1.71s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.025950067000003685,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3587524490000007,)
  5%|▍         | 18/394 [01:02<12:18,  1.96s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02873908400000147,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3630483779999949,)
  5%|▍         | 19/394 [01:03<10:44,  1.72s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02785992500000134,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.4346256749999995,)
  5%|▌         | 20/394 [01:06<12:36,  2.02s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03208756000000079,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31617836200000227,)
  5%|▌         | 21/394 [01:07<11:02,  1.78s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.0284931610000001,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31770587799999817,)
  6%|▌         | 22/394 [01:10<11:45,  1.90s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026672720999997068,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.32325969600000093,)
  6%|▌         | 23/394 [01:11<10:17,  1.66s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02935622500000079,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.4908445499999985,)
  6%|▌         | 24/394 [01:13<12:16,  1.99s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03152447500000477,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3169876740000035,)
  6%|▋         | 25/394 [01:15<10:42,  1.74s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.025980103999998505,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31829879300000385,)
  7%|▋         | 26/394 [01:17<12:10,  1.99s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.035267548000000204,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31970710399999547,)
  7%|▋         | 27/394 [01:18<10:34,  1.73s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027906903000001648,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.6355185849999998,)
  7%|▋         | 28/394 [01:21<12:45,  2.09s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.028026956999994468,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.32565844199999816,)
  7%|▋         | 29/394 [01:22<11:02,  1.82s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02839733900000141,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.31961535399999974,)
  8%|▊         | 30/394 [01:25<11:56,  1.97s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.030568225999999754,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.339091315999994,)
  8%|▊         | 31/394 [01:26<10:23,  1.72s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02683077900000086,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.33457976799999756,)
  8%|▊         | 32/394 [01:28<11:13,  1.86s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.028338861999998244,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.47980300300000067,)
  8%|▊         | 33/394 [01:29<09:50,  1.64s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02883012800000273,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.32673314000000175,)
  9%|▊         | 34/394 [01:32<12:50,  2.14s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.030187122999997484,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3295156840000004,)
  9%|▉         | 35/394 [01:34<11:01,  1.84s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.030338449000005596,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 178, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.3807768670000016,)
  9%|▉         | 36/394 [01:36<11:27,  1.92s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 162, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02777770599999485,)
slurmstepd: error: *** STEP 11778.0 ON studgpu-node09 CANCELLED AT 2024-05-02T21:48:22 ***
slurmstepd: error: *** JOB 11778 ON studgpu-node09 CANCELLED AT 2024-05-02T21:48:22 ***
