Running on host: studgpu-node09.inf.ethz.ch
In directory: /cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2
Starting on: Thu May 2 21:51:10 CEST 2024
SLURM_JOB_ID: 11779
Using cache found in /home/owendu/.cache/torch/hub/facebookresearch_WSL-Images_main
CUDA enabled
  0%|          | 0/394 [00:00<?, ?it/s]/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
/home/owendu/.local/lib/python3.10/site-packages/torch/functional.py:507: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3549.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-25.463449585,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.0336314219999991,)
  0%|          | 1/394 [00:31<3:29:17, 31.95s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.037252811999998414,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.6258857400000011,)
  1%|          | 2/394 [00:33<1:30:40, 13.88s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.0270306170000012,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.493613296999996,)
  1%|          | 3/394 [00:34<52:49,  8.11s/it]  --- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027184229999996035,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.37543464800000237,)
  1%|          | 4/394 [00:35<35:00,  5.38s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026961824000004242,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.393491197000003,)
  1%|▏         | 5/394 [00:36<25:10,  3.88s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02589302100000168,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.35294989500000185,)
  2%|▏         | 6/394 [00:38<19:18,  2.99s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026435435999999868,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.5952804269999987,)
  2%|▏         | 7/394 [00:39<15:31,  2.41s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02676518300000197,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.5224287380000021,)
  2%|▏         | 8/394 [00:40<13:03,  2.03s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02758385399999952,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.9987990859999982,)
  2%|▏         | 9/394 [00:41<11:21,  1.77s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02573036899999437,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.9286621669999988,)
  3%|▎         | 10/394 [00:43<11:34,  1.81s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02710822499999921,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.9652747020000021,)
  3%|▎         | 11/394 [00:45<11:00,  1.73s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027428282999999,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.0014161080000008,)
  3%|▎         | 12/394 [00:47<12:53,  2.02s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026428533000000698,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.081711281000004,)
  3%|▎         | 13/394 [00:49<11:29,  1.81s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027184415000000683,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.016035290000005,)
  4%|▎         | 14/394 [00:51<12:50,  2.03s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026003359999997144,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.7361828239999966,)
  4%|▍         | 15/394 [00:53<11:24,  1.81s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.03249703600000231,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.7297344059999986,)
  4%|▍         | 16/394 [00:56<13:37,  2.16s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02917303700000673,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.45524102600000305,)
  4%|▍         | 17/394 [00:57<11:48,  1.88s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02808359899999857,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.5352185989999967,)
  5%|▍         | 18/394 [01:00<13:31,  2.16s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.027236387000002082,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.8003352220000011,)
  5%|▍         | 19/394 [01:01<11:43,  1.87s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026262619000000598,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.5867772169999981,)
  5%|▌         | 20/394 [01:03<12:31,  2.01s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.028307675000000643,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.8009854859999948,)
  5%|▌         | 21/394 [01:04<10:57,  1.76s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.028504489999995997,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.575705425999999,)
  6%|▌         | 22/394 [01:07<13:10,  2.12s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026286470999998812,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.1385462379999964,)
  6%|▌         | 23/394 [01:08<11:25,  1.85s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.026638607999998953,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.0100854319999968,)
  6%|▌         | 24/394 [01:11<12:37,  2.05s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02716744399999982,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.0250177670000014,)
  6%|▋         | 25/394 [01:12<11:01,  1.79s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02653903599999552,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-1.0692998210000013,)
  7%|▋         | 26/394 [01:15<12:26,  2.03s/it]--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 163, in train_patches
    logging.info("forward pass:", t-time.process_time())
Message: 'forward pass:'
Arguments: (-0.02834904600000243,)
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/main.py", line 91, in <module>
    train_patches(opt)
  File "/cluster/courses/3dv/data/team-25/Faster-SLD/SceneLandmarkLocalization/src2/train.py", line 179, in train_patches
    logging.info("loss + backward pass:", t-time.process_time())
Message: 'loss + backward pass:'
Arguments: (-0.5185405240000023,)
slurmstepd: error: *** JOB 11779 ON studgpu-node09 CANCELLED AT 2024-05-02T21:52:38 ***
